package com.hall4.commons.db;

import java.sql.ResultSet;

public class QueryResult {
	
	private ResultSet resultSet;
	private int affectedRows;
	private int autoGeneratedKeyValue;
	
	public QueryResult() {
		resultSet = null;
		affectedRows = -1;
		autoGeneratedKeyValue = -1;
	}
	
	public ResultSet getResultSet() {
		return resultSet;
	}
	
	public int getAffectedRows() {
		return affectedRows;
	}
	
	public int getAutoGeneratedKey() {
		return autoGeneratedKeyValue;
	}
	
	public void setResultSet(ResultSet rs) {
		resultSet = rs;
	}
	
	public void setAffectedRows(int numRows)
	{
		affectedRows = numRows;
	}
	
	public void setAutoGeneratedKey(int idValue)
	{
		autoGeneratedKeyValue = idValue;
	}
}
