package com.hall4.commons.db;

import java.sql.ResultSet;
import java.util.LinkedList;

public class SQLQuery implements SQLSelectUpdate
{
	private final LinkedList<String> _variables;
	private String _query;
	private SQLQueryType _type;
	
	private ResultSet resultSet = null;
	private int affectedRows = -1;
	private int autoGeneratedKeyValue = -1;
	
	public SQLQuery(String query, SQLQueryType type) {
		_query = query;
		_type = type;
		_variables = new LinkedList<String>();
	}
	
	public void addVariable(String variable) {
		_variables.add(variable);
	}
	
	public SQLQueryType getType()
	{
		return _type;
	}
	
	@Override
	public String toString() {
		return _query;
	}
	
	public ResultSet getResultSet() {
		return resultSet;
	}
	
	public int getAffectedRows() {
		return affectedRows;
	}
	
	public int getAutoGeneratedKey() {
		return autoGeneratedKeyValue;
	}
	
	public void setResultSet(ResultSet rs) {
		resultSet = rs;
	}
	
	public void setAffectedRows(int numRows)
	{
		affectedRows = numRows;
	}
	
	public void setAutoGeneratedKey(int idValue)
	{
		autoGeneratedKeyValue = idValue;
	}

	@Override
	public LinkedList<String> getVariables() {
		return _variables;
	}
}
